CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    balance DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE Categories (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    description TEXT
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    category VARCHAR(255) NOT NULL REFERENCES Categories(name),
    description TEXT
);

CREATE TABLE AddedProducts (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL PRIMARY KEY REFERENCES Products(id)
);

CREATE TABLE Purchases (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    sid INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    order_number INT NOT NULL,
    PRIMARY KEY(order_number, id)
);

CREATE TABLE Supply (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    --seller_price DECIMAL(12,2) NOT NULL, -- If implementing seller specific instead of product specific price
    seller_inventory INT NOT NULL,
    PRIMARY KEY(uid, pid)
);

CREATE TABLE ProductReviews (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    review VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    review_time timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY(uid, pid)
);

CREATE TABLE Carts(
    uid INT NOT NULL References Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL DEFAULT 1,
    savedforlater BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (uid, pid, sid, savedforlater)
);

CREATE TABLE SellerReviews(
    uid INT NOT NULL REFERENCES Users(id),
    sid INT NOT NULL REFERENCES Users(id),
    review VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    review_time timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY(uid, sid)
);